### ISSUE TITLE
Goals and Roadmap

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo.io#5]
The current version of the site is meant as merely a starting place, so  thought I'd start a thread to record any ideas for this site beyond the short-term. Short-term Todos are reflected in issues, or on [todo.md](https://github.com/budparr/gohugo.io/blob/master/todo.md)

Feel free to jump in on this.

As a stated goal, beyond communicating Hugo's value to new and current users, the site and it's theme should exemplify Hugo's capabilities, as well as performance and accessibility best practices.

These are in no particular order.

- [ ] Code review by a community member. Show that it was reviewed, and when (like a quality stamp)
- [ ] Add "custom output types" (e.g. AMP) when available.
- [ ] Multilingual
- [ ] Service Workers for offline access (the site will already have a PWA manifest)

**Comment by rdwatters** [comment]
> Service Workers for offline access (the site will already have a PWA manifest)

👍 

Do you see this as a worthwhile effort for the docs as well? I guess if they live with source it won't matter because they'll always be available to be run locally...

**Comment by budparr** [comment]
> how nitpicky are we getting with this?

Not sure what you mean? Nitpicky with a particular element above, or adding more things?

**Comment by rdwatters** [comment]
Either. I meant do you want me to start adding issues like "use inline SVG for header logo" or are you looking to keep this and other threads more high-level/conceptual?

**Comment by budparr** [comment]
Oh, no. Go ahead and drop issues. Though  before you drop one about the inline SVG, you should be aware of this [commit](https://github.com/budparr/gohugo.io/commit/c959feaacd8fbb5b9fb979812aea91228d2ddd80) where I mentioned I dropped the file size from 260kb to 7kb by not doing inlining it. I'll take the HTTP request for that savings (plus, the site will be on HTTP2 and so # of requests will be moot because of multiplexing, as I understand it).

**Comment by rdwatters** [comment]
> I'll take the HTTP request for that savings (plus, the site will be on HTTP2 and so # of requests will be moot because of multiplexing, as I understand it).

If you look at the recent commits on the docs concept, I did the exact same thing. That said, maybe call for the svg rather than a PNG? Then you still get the resolution independence?

I noticed that inlining the logo in the site header doubled the HTTP requests and dropped my pagespeed score (not everything) down to 85/100...from 100/100.

**Comment by budparr** [comment]
> That said, maybe call for the svg rather than a PNG? 
Same file size for the SVG. Inlining itself isn't where the savings comes from.

> I noticed that inlining the logo in the site header doubled the HTTP requests
Not sure I follow this.

**Comment by rdwatters** [comment]
> Same file size for the SVG. Inlining itself isn't where the savings comes from.

Then why not use the SVG for resolution independence? And the savings *can* come since it's sent over with the HTML itself...

> Not sure I follow this.

I should have been clearer. This relates to Pagespeed score, which somehow dings you for total number of requests to show above-the-fold content, which is interesting, since whether `<img...` or `<svg...`, you would think it wouldn't make a difference, so I'm not sure why this was negatively affected... 

Maybe "embedding" rather than "inlining" is the more apposite choice. For example, all CSS is embedded in `<head>` even though it's technically no smaller than a minified/gzipped CSS file that's called separately...

OR maybe I'm just being anal retentive and we are talking about a site that's just going to be fast regardless. And I won't keep the perfect 100% score once we add the GitHub button and Google Analytics (even the asynchronous code). Go figure.

**Comment by budparr** [comment]
I meant it's the same size for the SVG file whether or not I inline it or call it in an image tag. It's 260kb. However, if I convert it to a PNG, it's 7kb. Seems like a good trade off to me for this use-case. Am I missing something here?

I am, however, loving using SVG's in Hugo, using `dict` to control size and fill. Super nice!

**Comment by rdwatters** [comment]
> Am I missing something here?

Gzipping and total HTTP requests. I'm pretty sure Netlify does both of these, right?

The network is the bottleneck, not just file size. Also, this is my bad for being lazy and not [SVGOMGing](https://jakearchibald.github.io/svgomg/) the logo. (I had to recreate it in Affinity Designer...with no image trace. Gah!) Give me a few minutes and I'll put up a better version :smile:

**Comment by rdwatters** [comment]
Thank you for pointing this out!

New file is down to 111kb but should be around 14k gzipped, but that's on it's own and not within HTML...although I doubt the HTML and XML will share strings for pointer replacements:

https://github.com/rdwatters/hugo-docs-concept/blob/master/layouts/partials/svg-icons/hugo-logo-wide.svg

I just added the embedded svg back to the header. Clearly not your use case, but if weighing the options in other contexts, there's always the advantage of styling/animating the SVG directly with CSS for a nicer separation of concerns.

> I am, however, loving using SVG's in Hugo, using `dict` to control size and fill. Super nice!

And this is why I referred to you as a "static mentor" for me in the Gitter channel. I wish I had thought of this before...

**Comment by budparr** [comment]
Nice job. Thanks!

> although I doubt the HTML and XML will share strings for pointer replacements:

you are one geeky dude :)

**Comment by rdwatters** [comment]
Bahaha. 

And to think I only wrote my first line of HTML in 2013. I promise I used to be a (relatively) cool guy:)

**Comment by budparr** [comment]
Well you seem to be doing pretty well. The compressed image is a big improvement. Now the svg is faster than the png and all is right with the world.

**Comment by rdwatters** [comment]
#perfmatters
#sodoesgettinglaid
#timetofindabalance

:smile: Glad it worked!
